apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-deployment-tenant1
   namespace: tenant1
spec:
   replicas: 1
   selector:
     matchLabels:
       app: nginx-tenant1
   template:
      metadata:
        labels:
           app: nginx-tenant1
      spec:
        containers:
        - name: nginx-tenant1
          image: nginx:1.20.1
          ports:
          - containerPort: 80